version:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11
py_impl:
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython
cross_target_platform:
  - "linux-armv7l"
zip_keys:
  - - version
    - py_impl
